#!/bin/bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

OPTIONS="suspend\nexitx\nreboot\nshutdown"

# source configuration or use default values
if [ -f $HOME/.config/rofi/power-config]; then
  source $HOME/.config/rofi/power-config
else
  LAUNCHER="rofi -width 10 -lines 4 -dmenu -i -p power:"
  USE_LOCKER="false"
  LOCKER="i3lock"
fi

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
  OPTIONS="exitx\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
      reboot)
        systemctl reboot
        ;;
      shutdown)
        systemctl poweroff
        ;;
      suspend)
        $($USE_LOCKER) && "$LOCKER"; systemctl suspend
        ;;
      exitx)
        i3-msg exit
        ;;
      *)
        ;;
    esac
fi
