#! /bin/sh

sxhkd &

compton -b

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d "wrk" "fox" "tre" "for" "fiv" "gmp" "svn" "ate" "com" "mzc"
bspc monitor -d "wrk" "fox" "com" "mzc"

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config focus_follows_pointer true

bspc config normal_border_color  "#000000"
bspc config focused_border_color "#d73737"
bspc config presel_border_color  "#BDB410"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# feh --bg-scale /home/apatel435/Pictures/red_forest.jpg
/home/apatel435/.config/polybar/launch.sh
