#! /bin/sh

sxhkd &

compton -b

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config focus_follows_pointer true

bspc config normal_border_color  "#6684E1"
bspc config focused_border_color "#60ac39"
bspc config presel_border_color  "#BDB410"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

feh --bg-scale /home/apatel435/Pictures/anime_night_sky.jpg
/home/apatel435/.config/polybar/launch.sh
